name: Deploy bot

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to remote server
      uses: appleboy/ssh-action@master
      with:
        host: vsecoder.me
        username: ubuntu
        password: ${{ secrets.SSH_PASSWORD }}
        script: |
          cd TomatoClanBot
          git pull
          sudo systemctl restart tomato
